### ISSUE TITLE
How does the executor calculate i32 binary opcodes?

### ISSUE THREAD

**Issue by Forpee** [wasmi-labs/wasmi#1092]
How come when I run a WASM like this:
```wat
(module
    (func (export "main") (result i32)
      i32.const 42
      i32.const 42
      i32.add
    )
)
```

the `Executor::execute` function in `src/engine/executor/instr.rs` immediately runs a `Instr::ReturnImm32`  without running ("matching") a `Instr::I32Add` beforehand.

Where is the "add computation" done if not in the loop?

**Comment by Robbepop** [comment]
I can currently only answer this in brief. The answer is that Wasmis WebAssembly to Wasmi bytecode translator that happens before a function is executed, performs constant folding. Thus the addition of the constant values happens during translation time and during execution no i32_add needs to be calculated since the result is pre-known.

**Comment by Forpee** [comment]
Thanks @Robbepop!

**Comment by Forpee** [comment]
@Robbepop Is there a way to turn this folding of constants feature off?
