### ISSUE TITLE
WASI: Can't open a file with both truncate and append flags

### ISSUE THREAD

**Issue by yagehu** [wasmi-labs/wasmi#861]
Compile this snippet with wasi-sdk and run it with wasmi will generate an invalid argument error.  It does NOT error on other runtimes like Wasmtime or on native Linux.

```
$ clang wasmi-creat.c
$ wasmi_cli --dir . a.out
executing File("a.out")::_start() ...
open: Invalid argument
```

```c
#include <fcntl.h>
#include <stdio.h>

int main(void) {
  int fd = open("a", O_CREAT | O_WRONLY | O_APPEND | O_TRUNC);
  if (fd == -1) {
    perror("open");
    return 1;
  }

  return 0;
}
```

**Comment by yagehu** [comment]
I believe this is a result of [this check in cap-std](https://github.com/bytecodealliance/cap-std/blob/3663202c6de1bc440764282524a21e14b924925d/cap-primitives/src/rustix/fs/oflags.rs#L83-L85). Wasmtime does not have this problem because it no longer uses cap-std in preview1.

**Comment by Robbepop** [comment]
Wasmi uses Wasmtime's WASI implementation because it is a huge amount of work to re-implement WASI yourself. However, since then their WASI implementation made it impossible for other runtime such as Wasmi to use newer versions and thus we cannot easily fix this problem.
Furthermore the WASI implementation for Wasmi was thankfully contributed externally by @OLUWAMUYIWA so I am not particularly expert in this part of the codebase.

There are 2 options forward to fix WASI issues for Wasmi:

1) Fork the old Wasmtime WASI implementation and provide patches.
    - Pros: Probably less work to fix bugs.
    - Cons: We are kinda stuck with WASI preview 1.
2) Provide our own WASI implementation.
    - Pros: We have full control of over WASI stack and can update it according to the spec.
    - Cons: A huge amount of (unpaid) work.

**Comment by yagehu** [comment]
Totally fair assessment.  I tested removing the check I linked in cap-std and it indeed works without it.  Apparently Wasmtime now uses `wasmtime-wasi` crate instead of `cap-std` so this issue is not observable in Wasmtime.  There might be a third option which is to use `wasmtime-wasi`.

**Comment by Robbepop** [comment]
You are welcome to experiment with integrating wasmtime-wasi into Wasmi. :)
