### ISSUE TITLE
Add `--verbose` mode to Wasmi CLI

### ISSUE THREAD

**Issue by tjpalmer** [wasmi-labs/wasmi#955]
I'd like to be able to avoid this message when running `wasmi_cli`:

```
executing File("examples/out/branch.wasm")::_start() ...
```

I'd prefer it off by default, reserved for verbose mode, but conservatively, some `--quiet` flag option could be available instead.

I'm happy to add `--quiet` on my end and submit a PR. Would this be ok?

**Comment by Robbepop** [comment]
Maybe it is indeed better to introduce a `--verbose` option to enable the current messages since that would reflect the default way that Wasmtime currently does with respect to non-warning or non-error messages.

Please feel free to open a PR to introduce this `--verbose` option to our Wasmi CLI tool. :)

**Comment by tjpalmer** [comment]
Awesome. Thanks for the reply. I'll work on that!
